"""Phase 5A: Canonical Metrics Reconciliation — Single source of truth for bot activity

Tracks and reconciles:
  - raw_candidates (generated by RDE)
  - rde_rejected (filtered by RDE)
  - paper_admission_attempts (sent to paper executor)
  - paper_entry_opened (successfully opened)
  - paper_entry_blocked (rejected before opening)
  - paper_exit_closed (closed)
  - learning_updates (canonical)
  - qualification_updates

Provides windows: 1h, 6h, 24h, since_start

Usage:
  from src.services.paper_activity_reconciler import PaperActivityReconciler
  reconciler = PaperActivityReconciler()
  stats = reconciler.get_stats(window="24h")
"""
import time
import logging
from typing import Dict, List, Optional, Tuple
from collections import defaultdict

log = logging.getLogger(__name__)

class PaperActivityReconciler:
    """Canonical metrics tracker for paper trading activity."""

    def __init__(self):
        self.start_time = time.time()

        # Per-window counters (1h, 6h, 24h, total)
        self._counters = {
            "raw_candidates": 0,
            "rde_candidates": 0,
            "rde_rejected": 0,
            "paper_admission_attempts": 0,
            "paper_entry_opened": 0,
            "paper_entry_blocked": 0,
            "paper_exit_closed": 0,
            "learning_updates": 0,
            "canonical_learning_updates": 0,
            "v5_learning_updates": 0,
            "qualification_updates": 0,
            "qualification_skips": 0,
            "outbox_flush_sent": 0,
            "outbox_flush_failed": 0,
        }

        # Time-windowed events for rolling calculations
        self._events = {
            "candidate": [],
            "admission_attempt": [],
            "entry_opened": [],
            "entry_blocked": [],
            "exit_closed": [],
            "learning_update": [],
        }

        # Rejection reason tracking
        self._rejection_reasons = defaultdict(int)
        self._block_reasons = defaultdict(int)

        # Segment breakdown
        self._segment_stats = defaultdict(lambda: {
            "entries": 0, "exits": 0, "learning": 0, "blocks": []
        })

        # Symbol/regime/side breakdown
        self._symbol_breakdown = defaultdict(lambda: {
            "entries": 0, "exits": 0, "blocks": 0
        })

    def record_candidate(self, symbol: str, side: str, bucket: str, source: str = "rde"):
        """Record a candidate signal generated."""
        self._counters["raw_candidates"] += 1
        if source == "rde":
            self._counters["rde_candidates"] += 1

        self._events["candidate"].append({
            "ts": time.time(),
            "symbol": symbol,
            "side": side,
            "bucket": bucket
        })

    def record_rde_rejected(self, symbol: str, reason: str):
        """Record a candidate rejected by RDE."""
        self._counters["rde_rejected"] += 1
        self._rejection_reasons[reason] += 1

    def record_admission_attempt(self, symbol: str, side: str, regime: str, bucket: str):
        """Record an attempt to open a paper position."""
        self._counters["paper_admission_attempts"] += 1
        self._events["admission_attempt"].append({
            "ts": time.time(),
            "symbol": symbol,
            "side": side,
            "regime": regime,
            "bucket": bucket
        })

    def record_entry_opened(self, position_id: str, symbol: str, side: str, regime: str, bucket: str):
        """Record successful paper entry."""
        self._counters["paper_entry_opened"] += 1
        self._events["entry_opened"].append({
            "ts": time.time(),
            "position_id": position_id,
            "symbol": symbol,
            "side": side,
            "regime": regime,
            "bucket": bucket
        })

        segment_key = f"{symbol}:{regime}:{side}"
        self._segment_stats[segment_key]["entries"] += 1
        self._symbol_breakdown[(symbol, side)]["entries"] += 1

    def record_entry_blocked(self, symbol: str, reason: str):
        """Record a blocked paper entry attempt."""
        self._counters["paper_entry_blocked"] += 1
        self._block_reasons[reason] += 1
        self._symbol_breakdown[(symbol, None)]["blocks"] += 1

    def record_exit_closed(self, position_id: str, symbol: str, side: str, regime: str, reason: str):
        """Record a closed paper exit."""
        self._counters["paper_exit_closed"] += 1
        self._events["exit_closed"].append({
            "ts": time.time(),
            "position_id": position_id,
            "symbol": symbol,
            "side": side,
            "regime": regime,
            "reason": reason
        })

        segment_key = f"{symbol}:{regime}:{side}"
        self._segment_stats[segment_key]["exits"] += 1
        self._symbol_breakdown[(symbol, side)]["exits"] += 1

    def record_learning_update(self, segment: str, source: str = "canonical"):
        """Record a learning update."""
        self._counters["learning_updates"] += 1
        if source == "canonical":
            self._counters["canonical_learning_updates"] += 1
        elif source == "v5":
            self._counters["v5_learning_updates"] += 1

        self._events["learning_update"].append({
            "ts": time.time(),
            "segment": segment,
            "source": source
        })

        self._segment_stats[segment]["learning"] += 1

    def record_qualification_update(self, skip: bool = False):
        """Record a qualification update or skip."""
        if skip:
            self._counters["qualification_skips"] += 1
        else:
            self._counters["qualification_updates"] += 1

    def record_outbox_flush(self, success: bool = True):
        """Record an outbox flush attempt."""
        if success:
            self._counters["outbox_flush_sent"] += 1
        else:
            self._counters["outbox_flush_failed"] += 1

    def get_stats(self, window: str = "24h") -> Dict:
        """Get stats for a time window.

        Args:
            window: "1h", "6h", "24h", or "total"

        Returns:
            Dict with reconciled metrics
        """
        now = time.time()

        # Calculate window seconds
        if window == "1h":
            window_s = 3600
        elif window == "6h":
            window_s = 6 * 3600
        elif window == "24h":
            window_s = 24 * 3600
        else:  # total
            window_s = now - self.start_time

        # Filter events by window
        def filter_events(events):
            return [e for e in events if now - e["ts"] <= window_s]

        candidates_windowed = filter_events(self._events["candidate"])
        attempts_windowed = filter_events(self._events["admission_attempt"])
        entries_windowed = filter_events(self._events["entry_opened"])
        exits_windowed = filter_events(self._events["exit_closed"])
        learning_windowed = filter_events(self._events["learning_update"])

        # Entry conversion funnel
        candidates_count = len(candidates_windowed)
        attempts_count = len(attempts_windowed)
        entries_count = len(entries_windowed)
        exits_count = len(exits_windowed)
        learning_count = len(learning_windowed)

        # Calculate conversion rates
        candidate_to_attempt = (attempts_count / candidates_count * 100) if candidates_count > 0 else 0
        attempt_to_entry = (entries_count / attempts_count * 100) if attempts_count > 0 else 0
        entry_to_exit = (exits_count / entries_count * 100) if entries_count > 0 else 0
        exit_to_learning = (learning_count / exits_count * 100) if exits_count > 0 else 0

        # Consistency checks
        is_consistent_exits_learning = (exits_count == learning_count or learning_count == 0)

        # Top rejection reasons
        top_rejections = sorted(self._rejection_reasons.items(), key=lambda x: x[1], reverse=True)[:5]
        top_blocks = sorted(self._block_reasons.items(), key=lambda x: x[1], reverse=True)[:5]

        # Segment stats
        segment_ranking = sorted(
            [(k, v) for k, v in self._segment_stats.items()],
            key=lambda x: x[1]["exits"],
            reverse=True
        )[:10]

        return {
            "window": window,
            "window_seconds": window_s,
            "uptime_seconds": now - self.start_time,

            # Counts
            "raw_candidates": candidates_count,
            "rde_candidates": self._counters["rde_candidates"],
            "rde_rejected": self._counters["rde_rejected"],
            "paper_admission_attempts": attempts_count,
            "paper_entry_opened": entries_count,
            "paper_entry_blocked": self._counters["paper_entry_blocked"],
            "paper_exit_closed": exits_count,
            "learning_updates": learning_count,
            "canonical_learning_updates": self._counters["canonical_learning_updates"],
            "v5_learning_updates": self._counters["v5_learning_updates"],

            # Conversion funnel
            "conversion": {
                "candidate_to_attempt": round(candidate_to_attempt, 2),
                "attempt_to_entry": round(attempt_to_entry, 2),
                "entry_to_exit": round(entry_to_exit, 2),
                "exit_to_learning": round(exit_to_learning, 2),
                "overall_candidate_to_closed": round((exits_count / candidates_count * 100) if candidates_count > 0 else 0, 2),
            },

            # Consistency
            "consistency": {
                "exits_matches_learning": is_consistent_exits_learning,
                "exits_count": exits_count,
                "learning_count": learning_count,
            },

            # Top issues
            "top_rejection_reasons": top_rejections,
            "top_block_reasons": top_blocks,

            # Top segments
            "top_segments_by_exits": segment_ranking,

            # Outbox health
            "outbox_flushes_sent": self._counters["outbox_flush_sent"],
            "outbox_flushes_failed": self._counters["outbox_flush_failed"],
            "outbox_health": "OK" if self._counters["outbox_flush_failed"] == 0 else "ISSUES",
        }

    def log_hourly_health(self):
        """Log hourly health check."""
        stats = self.get_stats(window="1h")

        consistency = "OK" if stats["consistency"]["exits_matches_learning"] else "MISMATCH"
        top_block = stats["top_block_reasons"][0] if stats["top_block_reasons"] else ("none", 0)

        log.info(
            f"[PHASE5_RECON] window=1h "
            f"candidates={stats['raw_candidates']} "
            f"attempts={stats['paper_admission_attempts']} "
            f"entries={stats['paper_entry_opened']} "
            f"exits={stats['paper_exit_closed']} "
            f"learning={stats['learning_updates']} "
            f"blocks={self._counters['paper_entry_blocked']} "
            f"top_block={top_block[0]}({top_block[1]}) "
            f"consistency={consistency}"
        )

# Global singleton
_reconciler = None

def get_reconciler() -> PaperActivityReconciler:
    """Get or create the global reconciler."""
    global _reconciler
    if _reconciler is None:
        _reconciler = PaperActivityReconciler()
    return _reconciler

def reset_reconciler():
    """Reset reconciler (for testing)."""
    global _reconciler
    _reconciler = PaperActivityReconciler()
